services:
  backend:
    env_file:
      - ./backend/.env
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend  # Mounts the whole backend dir for reload purposes
    networks:
      - app-network

  frontend:
    env_file:
        - ./frontend/.env
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
