services:
  backend:
    environment:
      - DATABASE_URL=sqlite:///./dev.db
      - CONFIG_PATH=config.yaml
      - SCHEMA_DIR_PATH=division_schemas
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend  # Mounts the whole backend dir for reload purposes
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - VITE_API_URL=http://localhost:8000
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
